name: Sponsor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Update
        run: pnpx sponsorkit --dir .
        env:
          GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          OPENCOLLECTIVE_KEY: ${{ secrets.OPENCOLLECTIVE_KEY }}

      - name: Commit
        run: |
          git config user.name 'GitHub Action'
          git config user.email 'kecrily@users.noreply.github.com'
          git add sponsors*
          git commit -m 'chore: update sponsors'
          git push
